### ISSUE TITLE
orderBy filter requires additional parameter to perform ordering

### ISSUE THREAD

**Issue by alena-cher** [freearhey/vue2-filters#1]
Heres the code that should work according to the documentation:
`<li v-for="user in orderBy(users, 'name')">`
but the sort will not work with this setup. But if we add another argument it will work:
`<li v-for="user in orderBy(users, 'name', 'name')">`

Same for the reverse sorting:
`<li v-for="user in orderBy(users, 'name', -1)">` - doesnt work
`<li v-for="user in orderBy(users, 'name', 'name', '-1')">` - works

I`ve checked the code for the orderBy filter. Seems the problem is in the way how the sortorder is retrieved and args array is adjusted after that and how the sortKey is retrieved after that. I can submit a pull request if needed.

**Comment by freearhey** [comment]
Thanks for the help!
