### ISSUE TITLE
Chaining Filters

### ISSUE THREAD

**Issue by reascr** [freearhey/vue2-filters#10]
Great module to easily grab some simple vue1 filters.. Works as expected, but how can we chain several filters. Specifically I'm working with an array, 

`<li v-for="workOrder in orderBy(workOrders, orderTerm, orderDesc)">`

works great but I also need to add a "filterBy".. I tried pipes but no go.. Please let me know what the correct sintax would be! 

Thanks

**Comment by reascr** [comment]
Actually, sorry about that, I had tried this method and for some reason it didn't work initially (probably typo) but not it works;

`li v-for="workOrder in orderBy(filterBy(workOrders, 'sample'), orderTerm, orderDesc)"`

In this case it filters by the word "sample" but also orders it by the orderTerm variable.. 

Thanks again for the plugin

**Comment by 8lbiasian** [comment]
> Actually, sorry about that, I had tried this method and for some reason it didn't work initially (probably typo) but not it works;
> 
> `li v-for="workOrder in orderBy(filterBy(workOrders, 'sample'), orderTerm, orderDesc)"`
> 
> In this case it filters by the word "sample" but also orders it by the orderTerm variable..
> 
> Thanks again for the plugin

that's great I am looking for something similar 

but how i can escape the filter? 
for example 

filterby image >> will show only image 
filterby video >> will show only video 

what if I want to show all?
