### ISSUE TITLE
Vue 3 support?

### ISSUE THREAD

**Issue by gaby64** [freearhey/vue2-filters#102]
is vue 3 support coming?

**Comment by gaby64** [comment]
as a collection of functions thats is, since vue 3 does away with pipe | filters

**Comment by freearhey** [comment]
No, there are no plans to support Vue 3.

**Comment by ken-playerlync** [comment]
@freearhey looks like it's still some thing that can be globally configured, per this documentation: https://v3.vuejs.org/guide/migration/filters.html#_3-x-update, scroll to the `Global filters` section, they can be registered and used within a $filters method call versus a pipe still... I am going to try this and let you know.

**Comment by benjdl** [comment]
Solution for Vue 3:

`main.js`
```
import filters from './filters/'

const app = createApp(App)

app.config.globalProperties.$filters = filters
```

`filters/index.js`
```
import currency from './modules/currency'

export default {
  currency
}
```

`filters/util/index.js`
```
copy past content of the original util/index.js file
```

`filters/modules/currency.js`

```
copy past content of the original currency.js file
```

`YourComponent.js`

```
<span>{{ $filters.currency(value) }}</span>
```

**Comment by alex98247** [comment]
You can use this lib [vue3-filters](https://www.npmjs.com/package/vue3-filters). It is adaptation vue2-filters for vue3.
