### ISSUE TITLE
Pluralize problem with 0

### ISSUE THREAD

**Issue by Anthelmed** [freearhey/vue2-filters#12]
Pluralize does not appear to be working with a value of 0
https://jsfiddle.net/2v1wurca/

**Comment by freearhey** [comment]
I don't see any problem. As I know in English zero is plural.

**Comment by emfinfo** [comment]
S is the sign of the plural. Zero can in no way apply to a plural, since mathematically zero represents an empty set (neither singular nor plural). The S is therefore bad! In any case in French since the 18th century. So this pluralize filter cannot be used in some languages!
