### ISSUE TITLE
filterBy implementation

### ISSUE THREAD

**Issue by IgniSerpens** [freearhey/vue2-filters#15]
I think filterBy implementation is wrong. It searches a substring in a whole string instead of searching by first letters. For example, if I type "W" for ["Whatson", "Power", "Slower"] I must find Whatson only - not all of this words.

P. S. I've looked for Vue 1.0 implementation - it is the same, so... may be it's not bad. But still I think it's not what it must be. May be there must be another filter - searchBy, for example... Like google-search.

**Comment by javisperez** [comment]
I like this idea but honestly, i think a parameter might be the best choice, because right now the `filterBy` is very useful as it is (to me at least), maybe that "startWith.." flag can be a parameter.

**Comment by freearhey** [comment]
Closed due to inactivity.
