### ISSUE TITLE
How to use Multiple filters in one loop ?

### ISSUE THREAD

**Issue by vikash2039** [freearhey/vue2-filters#16]
While working with a project i need to filter throw some of arguments like 'name', 'class', 'value' from one loop, so i used ` <div v-for="post in filterBy(projectlist, cityFilter, 'city' | localityFilter, 'city')" >` , but it is not working, also i could't able to figure it out .

**Comment by angelfernandezcic** [comment]
Any suggestions? I need to do 3 filters consecutive and i tried with the pipe but doesn´t work :(
`v-for="item in filterBy(items, this.selectedMethod, 'ID_METHOD_PAID') | filterBy(items, this.selectedBudget, 'ID_TYPE_MONEY')"`

**Comment by chriys** [comment]
As of right now I don't think so. Vue filters don't support complex operations. Meaning you can't chain them in a v-for. The solution would have been to use them in a computed property but they aren't available there. 
A solution might be to implement a callback to filterBy.

[Vue Filters Rendering](https://vuejs.org/v2/guide/syntax.html#Filters)

**Comment by rbreaves** [comment]
The answer is most likely to nest it - not pipe it. I am using orderBy and filter, but I assume you can nest them however you want. No idea about computing it or using a callback. While nesting does not look great it works fine for me.

```
<tr v-for="city in orderBy(cities,'name') | filterBy(cities, searchKey)">
```
to
```
<tr v-for="city in orderBy(filterBy(cities, searchKey),'name')">
```
