### ISSUE TITLE
Feature: Allow custom filters

### ISSUE THREAD

**Issue by alfonsobries** [freearhey/vue2-filters#17]
Will be great if you allow to create my own custom filters, for example i want to create one filter for format date with the moment library

Example:
```
{{ user.created_at | date: LTS }}
// calls moment(date).format('LTS');
```

**Comment by gorbypark** [comment]
This would be amazing.

**Comment by jofftiquez** [comment]
@alfonsobries @gorbypark [Morphling](https://github.com/jofftiquez/morphling#morph-date) has this.

**Comment by freearhey** [comment]
Closed due to inactivity.
