### ISSUE TITLE
how to use in v-model?

### ISSUE THREAD

**Issue by callmesoul** [freearhey/vue2-filters#21]
how to use in v-model?

**Comment by freearhey** [comment]
In Vue 2.* filters can only be used inside text interpolations ({{ }} tags). Here is why - https://vuejs.org/v2/guide/migration.html#Filters-Outside-Text-Interpolations-removed

**Comment by roncemer** [comment]
Terrible decision.  This makes it nearly impossible to get proper currency formatting in apps written with Vue.  As much as I hate Angular, this is a huge show-stopper for writing any apps in Vue which require numeric data entry.
