### ISSUE TITLE
Pluralize filter update

### ISSUE THREAD

**Issue by garhbod** [freearhey/vue2-filters#22]
Is there room to change the Pluralize filter?
My thoughts would be to make it use the following package
https://github.com/blakeembrey/pluralize

And split of the Ordinal's option(st, nd, rd, th) into another filter using this package
https://github.com/marlun78/number-to-words

Also exposing each filter to make them able to be imported individualy.

I don't want to bother forking and making a start without knowing that it could be something you are interested in.

**Comment by freearhey** [comment]
I think it's a great idea. Looking forward to your PR.
