### ISSUE TITLE
500 (Cannot read property 'slice' of undefined)

### ISSUE THREAD

**Issue by Imanullah** [freearhey/vue2-filters#29]
function limitBy (arr, n, offset) {
  offset = offset ? parseInt(offset, 10) : 0
  n = __WEBPACK_IMPORTED_MODULE_0__util_index__["a" /* default */].toNumber(n)
  return typeof n === 'number'
    ? arr.slice(offset, offset + n)
    : arr
}

error 
500 (Cannot read property 'slice' of undefined)

**Comment by freearhey** [comment]
Please provide more info about your environment since right now I can't reproduce this error.
