### ISSUE TITLE
0.2.0 breaks uglifyjs

### ISSUE THREAD

**Issue by xvaara** [freearhey/vue2-filters#30]
ERROR in static/js/vendor.ec67e09dea199da20c96.js from UglifyJs
Unexpected token: punc (() [./node_modules/vue2-filters/dist/vue2-filters.js:477,0][static/js/vendor.ec67e09dea199da20c96.js:49045,9]

**Comment by Wherefour** [comment]
+1 for this. I'm seeing it too.

**Comment by jezmck** [comment]
+1

**Comment by freearhey** [comment]
Thank you all for the help! Package is already updated and the error should disappear.

**Comment by jezmck** [comment]
Sadly, that's not fixed it for me.

Same error as above;
```
ERROR in static/js/vendor.9d951549d71db2926f90.js from UglifyJs
SyntaxError: Unexpected token punc «(», expected punc «:» [./~/vue2-filters/dist/vue2-filters.js:294,0]
```

**Comment by freearhey** [comment]
@jezmck please add some information about your environment so I can reproduce this bug itself.

**Comment by jezmck** [comment]
@Wherefour, did the update fix it for you?

I'm running MacOS X.
The error occurs when I `npm run build` which runs a WebPack script which, frankly, I don't understand.

**Comment by Wherefour** [comment]
Yes, it did. Thanks by the way @freearhey.

I'm using it in Rails 5.1 with Webpacker and Yarn, though, so you probably have a different build process. There is a way I can force compilation locally as if it is a "production" environment and that's how I tracked the failed build down to v0.2.0, so maybe you can try that on your end to help diagnose....?

**Comment by Wherefour** [comment]
Hmm, I was curious so tried to compile locally again and looks like it does fail that way:

`ERROR in wherefour-14da8b16eef7b8e38b3b.js from UglifyJs
Unexpected token: punc (() [./node_modules/vue2-filters/dist/vue2-filters.js:294,0][wherefour-14da8b16eef7b8e38b3b.js:49516,9]`

if I roll back to v1.9.0 it all compiles fine.....

**Comment by Wherefour** [comment]
v.0.1.9 I meant. lol

**Comment by Wherefour** [comment]
Not sure if this helps, but it looks like there is an open issue with webpacker 3.0.0 and Heroku: https://github.com/rails/webpacker/issues/739

If I specify v0.1.9 in package.json, it compiles locally. If I change the version to v0.2.0 or v0.2.1, it fails with the error.

Here's the package.json that DOES compile OK:

> {
  "name": "wfapp",
  "private": true,
  "engines": {
    "node": "^6.11.2",
    "yarn": "^0.27.5"
  },
  "dependencies": {
    "@rails/webpacker": "^3.0.0",
    "vue": "^2.4.2",
    "vue-bootstrap-datetimepicker": "^3.0.0",
    "vue-loader": "^13.0.4",
    "vue-resource": "^1.3.4",
    "vue-template-compiler": "^2.4.2",
    "vue2-filters": "^0.1.9"
  },
  "devDependencies": {
    "webpack-dev-server": "^2.7.1"
  }
}

**Comment by xvaara** [comment]
Didn't fix it for me. Here's how to replicate it:
https://asciinema.org/a/GDmVmMy0aFX93EDZeEKnMGa3r

**Comment by Ewocker** [comment]
Fail for me as well:
ERROR in static/js/vendor.fed95415f17c4112acf5.js from UglifyJs
Unexpected token: punc (() [./~/vue2-filters/dist/vue2-filters.js:294,0][static/js/vendor.fed95415f17c4112acf5.js:12184,9]

**Comment by gigaprakosa** [comment]
Fail for me too with the latest version. But fine with v.0.1.9.

**Comment by jekinney** [comment]
@gigaprakosa  stated, Current version: 

ERROR in static/js/vendor.efd6b4056f88cc059df7.js from UglifyJs
Unexpected token: punc (() [./~/vue2-filters/dist/vue2-filters.js:294,0][static/js/vendor.efd6b4056f88cc059df7.js:32548,9]

Rolled back to 0.19 good to go
