### ISSUE TITLE
Issue while building

### ISSUE THREAD

**Issue by Pronjaboy** [freearhey/vue2-filters#32]
I am getting this error when I try to npm run build:

`ERROR in build.js from UglifyJs
Unexpected token: punc (() [./~/vue2-filters/dist/vue2-filters.js:294,0][build.js:50404,9]
`
 
Help =(

**Comment by lukasborawski** [comment]
The same one @freearhey  can you help with this?

**Comment by Ewocker** [comment]
Fail for me as well:
`ERROR in static/js/vendor.fed95415f17c4112acf5.js from UglifyJs
Unexpected token: punc (() [./~/vue2-filters/dist/vue2-filters.js:294,0][static/js/vendor.fed95415f17c4112acf5.js:12184,9]`
