### ISSUE TITLE
IE11 Fix

### ISSUE THREAD

**Issue by joer80** [freearhey/vue2-filters#33]
I got an error in IE11 and fixed it by changing:

var Vue2Filters = {
  install(Vue) {

to:

var Vue2Filters = {
  install: function(Vue) {

Just wanted to let you know!

**Comment by autobrain-stanley** [comment]
Yes it seems this lib isn't transpiled with es2015 transforms so we aren't getting the transformed version of method property short hand

**Comment by autobrain-stanley** [comment]
Yes it seems this lib isn't transpiled with es2015 transforms so we aren't getting the transformed version of method property short hand
