### ISSUE TITLE
error when minify with UglifyJS

### ISSUE THREAD

**Issue by zhiga90** [freearhey/vue2-filters#35]
Unexpected token: punc (() [./~/vue2-filters/dist/vue2-filters.js:294,0]

**Comment by freearhey** [comment]
Which version vue2-filters are you using?

**Comment by zhiga90** [comment]
{
  "name": "vue2-filters",
  "version": "0.2.1",

**Comment by freearhey** [comment]
Please update to v0.2.2, like this:
`npm update vue2-filters`
and the error will disappear.
