### ISSUE TITLE
How can I call filte from my nuxt.js component

### ISSUE THREAD

**Issue by PrimozRome** [freearhey/vue2-filters#36]
I have installed the `vue2-filters` in nuxt like described in the docs. The filters are working in my component template like this `{{ someVaue | capitalize }}`.

How can I use these filters in my component inside methods? Something like this for example:

```
<script>
export default {
  methods: {
    someMethod () {
      this.value = someValue | capitalize
    },
  }
}
</script>
```

I have come up to that you can access your filters trough `this.$options.filters`. But in case of my component `this.$options.filters` returns and empty object `{}`?

**Comment by freearhey** [comment]
Yes, `this.$options.filters` inside nuxt.js returns an empty object for me, too. But despite this, the filters still work if you access them like this:

```js
...
someMethod () {
  this.capitalizedValue = this.$options.filters.capitalize(someValue)
},
...
```
