### ISSUE TITLE
orderBy with multiple orders

### ISSUE THREAD

**Issue by periscuelo** [freearhey/vue2-filters#47]
Hi thanks and congratulations for your work =)
I have one doubt.
Sometimes i need order by name and age for example. How i can do this?
Have something like this? orderBy(users, ['name', 'age'], -1)

It's possible make this with the plugin in any other form?

Thanks again.

**Comment by periscuelo** [comment]
I used _.orderBy of lodash to solve my problem. Thanks again.

**Comment by jimmywarting** [comment]
I wonder the same thing, but i don't want to include the hole lodash lib for just one thing

**Comment by periscuelo** [comment]
@jimmywarting then import only function of lodash as you need. Like below.
`import forEach from 'lodash/forEach'`
This way I only made import of the function I need and not the whole Lodash.

**Comment by jimmywarting** [comment]
i am kind of agains using lodash when there are mostly native solution for almost anything lodash dose

**Comment by periscuelo** [comment]
Then, you must be happy with a native solutions, use and share a lot. No one is forced to use anything. 😄
