### ISSUE TITLE
how to get the changed list made with orderBy ?

### ISSUE THREAD

**Issue by ctf0** [freearhey/vue2-filters#50]
lets say we have a list of 10 items, now when we use `orderBy` the list order will change but as the filter use a cloned list its not possible to make any operations on the original list as the index will be wrong.

so is there a way i could get that cloned list made by the filter ? 
or better yet mutate the original list instead ?
or if neither is good, maybe the filter could fire an event with the new list then i can use it to make operations without mutating the original list ?

**Comment by freearhey** [comment]
I think will be better mutate the original list.
