### ISSUE TITLE
Namespace methods (and maybe other filters)

### ISSUE THREAD

**Issue by kball** [freearhey/vue2-filters#52]
The array filters are implemented as methods in a mixin, which can cause problems if the names collide with methods in other components or mixins. (I just spent a couple hours tracking down why a 3rd party component wasn't working, and turned out they had a `prop` named `filterBy` that was getting clobbered by the `filterBy` method from `vue-filters`.

The names used are pretty common, so this is likely to cause many issues when you mix in the filters globally (as you do in Nuxt with a plugin).

Probably the best solution would be to namespace all the methods so they are unlikely to collide. E.g. `vfOrderBy` instead of `orderBy`. This could be optional so those who don't need it (they're using filters locally in a component instead of globally in an app) wouldn't have to use it.

**Comment by t0n1zz** [comment]
so the solution is? manual build?

**Comment by kball** [comment]
FWIW @t0n1zz @erikverbeek @akhoury I have implemented a version of this and submitted it as a PR. Would be happy for feedback on better approaches, or if you want to install directly from a branch I can create one that includes a recompiled distfile

**Comment by t0n1zz** [comment]
@kball oh yea i would love to try it...  i "must' need this package and on the other end i want to also adding select2 or something like that... to do search on select and multiple select but both of them just can't work together

**Comment by jgsnat** [comment]
I uploaded a change that I believe solves this problem. Now just wait to leave the new version

**Comment by kaiserkiwi** [comment]
Will this bug ever get fixed in a release version? The fix is now 27 days old but the last release version is from January.

**Comment by freearhey** [comment]
If you came across this bug please upgrade the package up to v0.4.0. In new version global mixins has been removed and errors must disappear.

Now in order to use methods such as `limitBy`, `filterBy `, `find ` or `orderBy `, you need to register `Vue2Filters.mixin` in the component manually, like so:

```js
import Vue2Filters from 'vue2-filters'

export default {
  ...
  mixins: [Vue2Filters.mixin],
  ...
}
```

Hope this helps.
