### ISSUE TITLE
Help me please ! urgent: I do not know how to do it

### ISSUE THREAD

**Issue by titoff002** [freearhey/vue2-filters#57]
Hello, 

Hello,
I would like on the action 'click' of a button executed action / filter "filberBy ()".

Do you have a complete example to provide me?

Here is a part of my code (but it does not work) :

```
<b-checkbox @input="filterBy(this.liste,'str_search','lib_name')"  v-model="search" >esrs</b-checkbox> 
<article  v-for="item in filterBy(this.liste)" :key="item.id"  :id="item.lib">
...
</article>
```

Thank you.

**Comment by freearhey** [comment]
Here is a small example: 
https://codepen.io/Arhey/pen/mQJPoz

I hope this helps you.
