### ISSUE TITLE
Nuxt SSR break on 4.0 window is not defined

### ISSUE THREAD

**Issue by julianpaulozzi** [freearhey/vue2-filters#59]
Version 4.0 with Nuxt 2.3.4 SSR ReferenceError window is not defined on node_modules\vue2-filters\dist\vue2-filters.js line 10.

**Comment by eskimm** [comment]
Same issue with latest Nuxt

**Comment by freearhey** [comment]
Thank you both! I was able to reproduce the error and working on it.
