### ISSUE TITLE
Different currencies

### ISSUE THREAD

**Issue by javierorbaquoters** [freearhey/vue2-filters#6]
Hello, 

is there any way to use different kinds of currencies on the currency filter?
For instance, {{ data.result | currency | € }} to display the currency in euros?

Thank you

**Comment by freearhey** [comment]
Yes, it can be done. Here is an example from the docs: `{{ amount | currency('£') }}` (https://github.com/freearhey/vue2-filters#currency)

**Comment by zziippee** [comment]
Is it possible to use Indian Currency Format ₹1,00,00,000.00?
Watch the comma position

**Comment by freearhey** [comment]
@zziippee no, at the moment it is not possible
