### ISSUE TITLE
v0.4.0 orderBy is not defined error

### ISSUE THREAD

**Issue by malipetek** [freearhey/vue2-filters#60]
New release throwing this error on every instance.

`ReferenceError: orderBy is not defined`.

Error disappears when `orderBy` is replaced with `Vue2Filters.mixin.methods.orderBy` in template.

Error log is attached below:
[v4.0.0_error.log](https://github.com/freearhey/vue2-filters/files/2623230/v4.0.0_error.log)

**Comment by freearhey** [comment]
Have you added `Vue2Filters.mixin` to your component mixin list?
