### ISSUE TITLE
Unit testing examples

### ISSUE THREAD

**Issue by andrewbrntt** [freearhey/vue2-filters#62]
I am trying to write unit tests for a component that uses the ```pluralize``` filter, but I cannot seem to get it to work. I came here looking for some examples on how to import it as part of a test, but there seems to be no documentation on how to properly mock it out. If you could add some testing examples to your documentation, it would be greatly appreciated. Thanks

**Comment by freearhey** [comment]
Hi! To be honest, I don't really understand what kind of example you mean. Maybe you can give me a link to another library where it's done.
