### ISSUE TITLE
Capitalize not capitalizing every word by default

### ISSUE THREAD

**Issue by warrebuysse** [freearhey/vue2-filters#66]
As per the docs, the `capitalize` function should capitalize every separate word in the string. By default, our `item.supplier` is all capitals. I use the `lowercase` filter to lowercase everything, and use `capitalize` to capitalize the words. 

So in short: 
Initial string: "SOME STRING"
After lowercase: "some string"
After capitalize: "Some string"

I tried setting the prop `onlyFirstLetter` to false, but that doesn't work.

```
annotations.push({
  icon: 'briefcase',
  title: this.$options.filters.capitalize(
    this.$options.filters.lowercase(item.supplier),
  ),
});
```

**Comment by freearhey** [comment]
Strange, that's what I get: https://codepen.io/Arhey/pen/YMLzda
