### ISSUE TITLE
CSP eval() error

### ISSUE THREAD

**Issue by dennis47528** [freearhey/vue2-filters#67]
vue2-filters doesn't work with a secure/strong CSP.
Currently, vue2-filters only works if you add the **unsafe**-eval CSP directive. **Bad practice and unsafe!**

I have to use version 0.3.0 because **multiple** eval()'s are used in newer versions.

Example:

https://github.com/freearhey/vue2-filters/blob/d9ac0e2d3b7807e01f8aed86d6699e9f9954b67c/dist/vue2-filters.js#L106-L107

**Comment by freearhey** [comment]
Thank you for bringing this issue to my attention. I'll try to figure it out and resolve it by the next release.
