### ISSUE TITLE
(TS) Could not find a declaration file for module 'vue2-filters'. '/node_modules/vue2-filters/dist/vue2-filters.js' implicitly has an 'any' type.   Try `npm install @types/vue2-filters` if it exists or add a new declaration (.d.ts) file containing `declare module 'vue2-filters'

### ISSUE THREAD

**Issue by momoski** [freearhey/vue2-filters#68]
I get this error when trying to use it in my Vue2 project along with Typescript on this line
`import Vue2Filters from "vue2-filters";`

> (TS) Could not find a declaration file for module 'vue2-filters'. '/node_modules/vue2-filters/dist/vue2-filters.js' implicitly has an 'any' type.   Try `npm install @types/vue2-filters` if it exists or add a new declaration (.d.ts) file containing `declare module 'vue2-filters

**Comment by Shinigami92** [comment]
@freearhey Have you tested it? Can we have a v0.6.1 soon?

**Comment by freearhey** [comment]
@Shinigami92 Done.
