### ISSUE TITLE
Options to show sign(+) for positiv numbers

### ISSUE THREAD

**Issue by MaximilianFranke** [freearhey/vue2-filters#76]
It would be nice to have a option that adds a + symbol to positv numbers like:
`+1.245,35€`

It would be helpfull to format amount changes.

**Comment by freearhey** [comment]
But isn’t it easier to add a plus sign when displaying the price on the screen, like this:

```html
<span>+{{ price | currency('€') }}</span>
```

or am I misunderstood?

**Comment by freearhey** [comment]
Closed in favor of #77

**Comment by MaximilianFranke** [comment]
But with an negative amount this would be  display:  +-1.245,35€
Sure i can add a conditional + sign but for me this would be nice to have it as option in the filter.
