### ISSUE TITLE
How to pre-configure filters?

### ISSUE THREAD

**Issue by NBaron** [freearhey/vue2-filters#78]
Hello,

We would like to pre-configure a filter in order to ease its usage.
Usually, we need to pass the same arguments for the same filter used at various places.
But other places will need a different arguments set.

As an example, regarding the currency filter, we would like to write something like:
`{{value | currencyEuro}}`
which would be equivalent to:
`{{value | currency('€', 2, {
            thousandsSeparator: " ",
            spaceBetweenAmountAndSymbol: true,
            symbolOnLeft: false})}}`

**and**

`{{value | currencyUsDollar}}`
which would be equivalent to:
`{{value | currency('$', 2, {
            thousandsSeparator: "'",
            spaceBetweenAmountAndSymbol: true,
            symbolOnLeft: true})}}`

I have tried to define a custom filter named currencyEuro, but I cannot use another filter in the implementation code.

Any suggestions on how to achieve that?

**Comment by freearhey** [comment]
Honestly, I don't have any idea how to implement exactly what you described.

All I can do is suggest that you do a simple [mixin](https://vuejs.org/v2/guide/mixins.html) instead, which you can also use throughout the application. Here is a small example of how this might look: https://codepen.io/arhey/pen/OJJdBrx

**Comment by NBaron** [comment]
Thank you for this quick reply.
This is a good solution as it conveys simplicity, readability and can be defined globally with global mixins.
