### ISSUE TITLE
Any plans for a file size filter?

### ISSUE THREAD

**Issue by xJREB** [freearhey/vue2-filters#79]
I was wondering if a file size filter would be a welcome addition. We use such a filter in some projects. Maybe we could outsource it here?

This is the function we are currently using:

```javascript
// Convert a fileSize in bytes to a human readable string
export const fileSizeFilter = (sizeInBytes: number): string => {
  if (sizeInBytes >= 1024 * 1024 * 1024) {
    // GB
    return `${(sizeInBytes / (1024 * 1024 * 1024)).toFixed(2)} GB`;
  } else if (sizeInBytes >= 1024 * 1024) {
    // MB
    return `${(sizeInBytes / (1024 * 1024)).toFixed(2)} MB`;
  } else if (sizeInBytes >= 1024) {
    // kb
    return `${Math.round(sizeInBytes / 1024)} kb`;
  }
  // byte
  return `${sizeInBytes} byte`;
};
```

Feel free to make suggestions for improvement. If you think this is a good idea, I'll happily provide a pull request.

**Comment by freearhey** [comment]
I think it's a great idea 👍

I would only add the ability to change the number of digits after the decimal point. Otherwise, everything looks fine to me.

**Comment by freearhey** [comment]
I just published a beta version of the library with a new filter to npm - `v0.9.0-beta.0`

Basically it's the same code that you sent me, I just replaced the filter name with a more general `bytes` and added the ability to set the number of digits after the decimal point globally. 

It would be great if you could check out this version and if everything is okay then I will publish a new release.

**Comment by xJREB** [comment]
Sorry for the late response! The `bytes` filter worked nicely for me. I think you can publish a non-beta realease with it.

**Comment by freearhey** [comment]
Done. Release `v0.9.0` is available for download.

Thanks for your help!

**Comment by xJREB** [comment]
My pleasure! I may even provide some suggestions for additional filters in the future... 🙃
