### ISSUE TITLE
Number filter throwing an error in IE 11

### ISSUE THREAD

**Issue by hammadmansuri** [freearhey/vue2-filters#81]
While using number filter like below
`{{123 | number('0.00')}}`

I'm getting an error saying that,

> [Vue warn]: Error in render: "TypeError: Object doesn't support property or method 'sign'"

If I remove number filter, page loads up fine. It's working fine in other browsers. My vue2-filters version is 0.8.0

**Comment by hammadmansuri** [comment]
Great!!

It solved the problem. Thanks @freearhey 

Also, I'm new to versioning system. So, how and when this fix will get roll into major version? (As this one is beta, can't use in production build)

**Comment by freearhey** [comment]
Good! I'll try to publish the final version as soon as possible and write here after that.

**Comment by hammadmansuri** [comment]
Thanks @freearhey  Appreciated

**Comment by freearhey** [comment]
Done, version `0.9.1` available for download.
