### ISSUE TITLE
Conflicts with vue2-filters plugin after registering it globally.

### ISSUE THREAD

**Issue by manjunath-coachthem** [freearhey/vue2-filters#82]
Hi,

I am using vue2-filters plugin in my project and I have registered it globally. 

Now In the child component I have installed another plugin called vue-select which internally uses some method/props names from vue2-filters and because of this Vue throws a warning as shown below and also some features of vue-select is not working because of vue2-filters method/props name getting override

![Screenshot from 2019-12-26 20-37-20](https://user-images.githubusercontent.com/24474128/71506404-c3a0d100-28a6-11ea-9b9f-cfb5a033f09e.png)

**Comment by freearhey** [comment]
Please specify which version of vue2-filters you are using.

**Comment by manjunath-coachthem** [comment]
I am using **"vue2-filters": "^0.3.0"** and **"vue-select": "3.3.0"**

**Comment by freearhey** [comment]
Oh, now I see. This problem was solved more than a year ago in [v0.4.0](https://github.com/freearhey/vue2-filters/releases/tag/v0.4.0). To make the error disappear, just upgrade to the latest version. At the moment, this is `v0.9.1`

**Comment by manjunath-coachthem** [comment]
Thanks @freearhey for your help
