### ISSUE TITLE
Change the number of digits after the decimal point does not work when rounding

### ISSUE THREAD

**Issue by aj-ee** [freearhey/vue2-filters#87]
```javascript
{{ 10.998 | number('0.00') }} // => 10.00

{{ 10.998 | number('0.000') }} // => 10.998

{{ 10.990 | number('0.00') }} // => 10.99
```
If the truncated digits are not zero, all digits after the decimal place are replaced with zeroes

**Comment by freearhey** [comment]
@aj-ee I just published `v0.11.1-beta.0` where rounding up these numbers should work as expected. 

Please check it on your side. If everything's okay, I'll make a new release then.

**Comment by xolott** [comment]
I'm having this issue too. With the beta release, I can confirm this doesn't happen anymore.

```js
{{ 23.961 | number('0.0') }} // => 24.0
```

Thanks

**Comment by freearhey** [comment]
@xolott Thank you for your feedback! 

I've just published a [new version](https://github.com/freearhey/vue2-filters/releases/tag/v0.11.1) of the library and hopefully the topic can finally be closed.
