### ISSUE TITLE
Option for NaN value for currency filter

### ISSUE THREAD

**Issue by Jonas-Jo** [freearhey/vue2-filters#88]
It would be nice to have an option to set the displayed value for NaN values. 
Example: 
{{ 1234 | currency('€', {nanValue: '-'}) }} --> '1234.00€'
{{ "NaN" | currency('€', {nanValue: '-'}) }} --> '-'

**Comment by freearhey** [comment]
You can achieve the same result this way:
```js
{{ value | currency('€') || '-' }}
```
