### ISSUE TITLE
number() option thousandsSeparator does not work

### ISSUE THREAD

**Issue by jogidoc** [freearhey/vue2-filters#90]
`
{{18850 | number('0.00', {'thousandsSeparator':'.','decimalSeparator':','}) // => 18850,00
`
Thousands separator is missing.

**Comment by freearhey** [comment]
You can get the result you want like this:
```js
{{ 18850 | number('0,0.00', { 'thousandsSeparator': '.', 'decimalSeparator': ',' }) }} // => 18.850,00
```
