### ISSUE TITLE
Vue2Filters is not defined error on single html page

### ISSUE THREAD

**Issue by RaviRamDhali** [freearhey/vue2-filters#91]
I have a single HTML page which is working with VueJs as expected. However when I try to use/load 
vue-filter.min.js and mixins: [Vue2Filters.mixin] I get the follow error 

**Uncaught ReferenceError: Vue2Filters is not defined**

```
<!-- VueJs -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/vue/2.6.10/vue.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/vue-filter/0.2.5/vue-filter.min.js"></script>
```

```
     <script type="text/javascript">
            new Vue({
                mixins: [Vue2Filters.mixin],
                el: "#app",
                data: {
                    error: false,
                    customerid: customerId,
                    customer: [],
                    discountcodeTotal : 0
       }
```

I am not sure if its the placement of mixins call or if I am missing something else.

Any help would be appricated.

**Comment by freearhey** [comment]
Try using the latest version of the library from here: `https://cdn.jsdelivr.net/npm/vue2-filters/dist/vue2-filters.min.js`
