### ISSUE TITLE
Thousand separate when using pluralize

### ISSUE THREAD

**Issue by rlightner** [freearhey/vue2-filters#92]
Currently having to use the following to get `1,000 items`

`{{ row.value | number('0,0') }}{{ row.value | pluralize('items) }}`

Is there a better way?

**Comment by freearhey** [comment]
As an option, you can combine both values in a computed property, like this:

```js
{
  //...
  computed: {
    formattedItems() {
      return this.rows.map(row => {
        const stringValue = this.$options.filters.number(row.value, '0,0') + this.$options.filters.pluralize(row.value, ' item')
        
        return { ...row, stringValue }
      })
    }
  },
  //...
}
```

This way the notation in the template will be slightly shorter:

```html
{{ row.stringValue }}
```

Here's a working example: https://codepen.io/arhey/pen/poEwZYb.

This is probably the only solution I see in this case.
