### ISSUE TITLE
FilterBy object inside another object

### ISSUE THREAD

**Issue by ghostlexly** [freearhey/vue2-filters#93]
Hello,
Is it possible to filter an object inside another object ?

Example:

`
this.housekeepers = this.filterBy(this.housekeepersNoFilters, 1, "nextDays.dayOfWeek");
`

To filter by dayOfWeek object inside nextDays object.

Regards

**Comment by freearhey** [comment]
Yes, it is possible. Here is an example: https://codepen.io/arhey/pen/abmXbxb
