### ISSUE TITLE
filterBy could be better.

### ISSUE THREAD

**Issue by aeadedoyin** [freearhey/vue2-filters#96]
Hey freearhey, 

Thanks for this library. Used it in quite a number of projects.
Just thinking the `filterBy` predefined method could be better. 

At the moment it just checks if query is included in value. 
It could have a new option that provides the operator to be used, say `>, >= <, <=, ==, !=`
This allows for exact filtering and more filtering possibilities.

**Comment by freearhey** [comment]
Hi,

That's a good idea! 
I will try to implement such a feature as soon as I have some free time.

**Comment by freearhey** [comment]
I studied this question and came to the conclusion that most of the tasks that will solve this feature can already be solved with the help of a custom function, like so:

```
<div v-for="user in filterBy(users, user => user.age > 16 && user.age <= 60)">
```

So I'm closing this issue for now, but anyway let me know if it's still not enough.
