### ISSUE TITLE
[Feature request] Add billions (B) and trillions (T) units to number filter

### ISSUE THREAD

**Issue by tsulli** [freearhey/vue2-filters#99]
Hi freearhey, thanks for the helpful filters! 

We're using them in a project launching soon and while the number filter units work great for numbers in the thousands (K) or millions (M), we have a need to use it for numbers in the billions (B) and trillions (T) as well. Would it be possible to get those added? Happy to submit a pull request too, if you accept those. Thanks!

**Comment by freearhey** [comment]
Yes, of course I do.

**Comment by freearhey** [comment]
Release `v0.13.0`
